FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore src/AuroraPortalB2B.Host/AuroraPortalB2B.Host.csproj
RUN dotnet publish src/AuroraPortalB2B.Host/AuroraPortalB2B.Host.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5248
ENV ASPNETCORE_URLS=http://0.0.0.0:5248
ENTRYPOINT ["dotnet", "AuroraPortalB2B.Host.dll"]
